### ISSUE TITLE
The "reading" field fails to display correctly on macos when it is enclosed as a list

### ISSUE THREAD

**Issue by loaphage** [cademcniven/cademcniven.com-dev#1]
Not sure if this is the right place to report this but when using your Eminent Note Type V2.3 on the latest anki (2.1.55, qt6) on macos if the pitch readings are in a list (ie >1 possible reading) it displays like the attached image. This happens if it is an ul or an ol, and if there is only one list element. Looks fine in windows (also 2.1.55, qt6). 

Is there an easy fix for this? I'm using your settings in yomichan, if there is no fix how can I change the template rules to just use the first reading outside of a list (as for a word with only one pitch definition)?
<img width="207" alt="anki" src="https://user-images.githubusercontent.com/107265294/211217394-c8782d76-284b-4da7-abb0-e2d6d57d85b4.png">

**Comment by cademcniven** [comment]
Someone else reported this issue before on 2.1.54 -- the issue *seems* to be related to qt6, because switching to qt5 fixed the issue. Sadly, this doesn't seem to be reproducible on windows (as you pointed out), so I'm not entirely sure how to go about finding a fix for it. 

I'll look into getting an OSX VM running to see if I can reproduce it. If not, I can *probably* come up with a handlebars fix

**Comment by loaphage** [comment]
Setting up a vm is more effort than I would expect, so I appreciate it. I should mention it's the apple silicon (arm) build. Unfortunately there isn't an mac arm build for qt5.

If it's a qt issue I assume it's to do with [WebEngine](https://addon-docs.ankiweb.net/porting2.0.html#webview-changes)(?). I tried following the debug steps (with the env var) to load a card in chrome but it just didn't connect, as if there is no service running on the port.

**Comment by cademcniven** [comment]
In the [2.1.55 release notes](https://github.com/ankitects/anki/releases/tag/2.1.55) I found the line

> On macOS, dark mode now uses the default macOS styling; you can optionally force behavior
like the other platforms with the following in the debug console: `mw.pm.set_force_custom_styles(True)`.

It's possible these default macOS stylings are what's changing the behavior. You can try that to see if it fixes it if you want, in the meantime, I'm still trying to get the stupid vm to work lmao

**Comment by loaphage** [comment]
That command didn't seem to do anything at all, but it would be a little unexpected if it did fix it as I upgraded from 2.1.54 to try and fix this issue.

**Comment by loaphage** [comment]
OK this is a solution, I'm not a webdev or anything so please tell me if there are some other implications to this.
Change the card styling css in anki to:
`ul, ol {
	list-style: none;
	margin-left: 0;
	padding-left: 0;
	display: inline-block;
}`

In other words changing the "display" from inline to inline block for lists. 

Haven't tested this on many cards yet but I don't see why it would only work on some.

<img width="234" alt="inline-block" src="https://user-images.githubusercontent.com/107265294/211286786-beb1911b-1af2-48a5-ba4d-31398e111d4a.png">

**Comment by cademcniven** [comment]
Oh nice! I was pretty sure it would be something related to display/position but wasn't entirely sure without testing it myself. I'll add those changes to my cards as well to make sure it doesn't cause any unexpected side-effects on windows. If all's good, I'll include that on the next release.

**Comment by rinbega** [comment]
It might be caused by using scaling other than 100% with the QT6 version of Anki.

![Screenshot from 2023-03-11 14-17-26](https://user-images.githubusercontent.com/47411817/224484320-5e109a2b-2c3d-4480-9ab5-18e0ef6a9e29.png)

If anyone has a similar issue, adding this to the CSS fixes it for now:

```css
ruby {
  display: inline-flex;
  flex-direction: column-reverse;
}

rt ol {
  margin: 0;
}
```

![Screenshot from 2023-03-11 14-18-19](https://user-images.githubusercontent.com/47411817/224484323-4f26aed0-b9a3-42fd-bdba-74c5ea0a5d21.png)
